name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Generate wrapper jar
        run: gradle wrapper --gradle-version 8.14 --distribution-type bin
      - name: Build plugin
        run: ./gradlew build --no-daemon
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: align-carets-plugin
          path: build/distributions/*.zip
